[package]
name = "rusty-pub-sub"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static="1.4.0"

[lib]
name = "server"
path = "src/server/lib.rs"

[[bin]]
name = "server"
path = "src/server/main.rs" 

[[bin]]
name = "client"
path = "src/client/main.rs"
